### PR TITLE
Clarify who is intended to post in the blog

### PR DESCRIPTION
**Pull request by Kleidukos**
The previous wording was unclear and vague. This list can be expanded if we missed anyone.

### CODE REVIEW

**Review by rebeccaskinner — APPROVED** [review]
This looks good to me. I like having each team called out here specifically.

**Comment by Tritlo** [comment]
We should add the podcast team: 

```
* The [Haskell Interlude Podcast](https://haskell.foundation/podcast/)
```

**Comment by jmct** [comment]
This LGTM

**Review by jmct — APPROVED** [review]
Looks great!

**Pull request merged**
